routes/web.php
<?php

use App\Http\Controllers\Controller;
use App\Http\Controllers\CutiController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PegawaiController;
use App\Http\Controllers\JabatanController;
use App\Http\Controllers\DivisiController;
use App\Http\Controllers\PresensiHarianController;
use App\Http\Controllers\RiwayatJabatanController;
use App\Http\Controllers\PeraturanController;
use App\Http\Controllers\RiwayatDivisiController;
use App\Http\Controllers\RekapPresensiController;
use App\Http\Controllers\RekapCutiController;


use App\Http\Controllers\DownloadFileController;
use App\Http\Controllers\Hrd\HrdPengajuanCutiController;
use Illuminate\Support\Facades\Mail;
use PhpOffice\PhpSpreadsheet\Chart\Layout;


use App\Http\Controllers\AuthController;
use App\Http\Controllers\Dashboard;
use App\Http\Controllers\PasswordController;
use App\Http\Controllers\ForgotPasswordController;
use App\Http\Controllers\GajiController;
use App\Http\Controllers\Hrd\HrdDashboardController;
use App\Http\Controllers\ManajemenPerusahaanController;
use App\Http\Controllers\ManajemenRoleMenuController;
use App\Http\Controllers\PenilaianKinerjaController;
use App\Http\Controllers\PotonganController;
use App\Http\Controllers\ResetPasswordController;
use App\Http\Controllers\ProfilController;
use App\Http\Controllers\ReportKinerjaController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\Staff\StaffCutiController;
use App\Http\Controllers\Staff\StaffDashboardController;
use App\Http\Controllers\Staff\StaffPengajuanCutiController;
use App\Http\Controllers\SuratPeringatanController;
use App\Http\Controllers\TunjanganController;
use Illuminate\Support\Facades\Auth;
use RealRashid\SweetAlert\Facades\Alert;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// DI SINI ADALAH ROUTES UNTUK MENU LOGIN //
Route::get('/', [AuthController::class, 'index'])->name('login');
Route::get('/logout', [AuthController::class, 'logout'])->name('logout');


// Reset Password
Route::get('/forget-password', [ForgotPasswordController::class, 'getEmail'])->name('forget-password.getEmail');
Route::post('/forget-password/postEmail', [ForgotPasswordController::class, 'postEmail'])->name('forget-password.postEmail');
Route::get('/reset-password/{token}', [ResetPasswordController::class, 'getPassword'])->name('reset-password.getPassword');
Route::post('/reset-password', [ResetPasswordController::class, 'updatePassword'])->name('reset-password.updatePassword');


Route::group(['middleware' => ['auth']], function () {

    //Search
    Route::get('/pegawai/search/', [SearchController::class, 'pegawai'])->name('pegawai.search');
    Route::get('/penilaian/search/', [SearchController::class, 'penilaian'])->name('penilaian.search');
    Route::get('/riwayatJabatan/search/', [SearchController::class, 'riwayatJabatan'])->name('riwayatJabatan.search');
    Route::get('/riwayatDivisi/search/', [SearchController::class, 'riwayatDivisi'])->name('riwayatDivisi.search');
    Route::get('/rekapPresensi/search/', [SearchController::class, 'rekapPresensi'])->name('rekapPresensi.search.pegawai');
    Route::get('/rekapCuti/search/', [SearchController::class, 'rekapCuti'])->name('rekapCuti.search.pegawai');
    Route::get('/gaji/search/', [SearchController::class, 'gaji'])->name('gaji.search.pegawai');
    Route::get('/report/search/', [SearchController::class, 'report'])->name('report.search.pegawai');
    Route::get('/presensi/search/', [SearchController::class, 'presensi'])->name('presensi.search.data');
    Route::get('/cuti/search/', [SearchController::class, 'cuti'])->name('cuti.search.data');


    //Rekap Presensi Pegawai
    Route::resource('rekapPresensi', RekapPresensiController::class);
    Route::get('/rekapPresensi/tahun/{data}', [RekapPresensiController::class, 'search'])->name('rekapPresensi.search');


    //Rekap Cuti Pegawai
    Route::resource('rekapCuti', RekapCutiController::class);
    Route::get('/rekapCuti/tahun/{data}', [RekapCutiController::class, 'showYear'])->name('rekapCuti.showYear');


    //Profil
    Route::resource('/profil', ProfilController::class);


    // Ganti Password
    Route::resource('/pass', PasswordController::class);


    //Cuti Staff
    Route::resource('staffCuti', StaffCutiController::class);
    Route::post('/staffCuti/tahun/', [StaffCutiController::class, 'tahunCuti'])->name('staffCuti.search');


    //Pengajuan Cuti
    Route::resource('staffPengajuanCuti', StaffPengajuanCutiController::class);
    Route::put('/staffPengajuanCuti/keputusan/{data}', [StaffPengajuanCutiController::class, 'keputusan'])->name('staffPengajuanCuti.keputusan');


    // Dashboard Admin
    Route::resource('superAdmin', Dashboard::class);


    // Dashboard HRD
    Route::resource('hrd', HrdDashboardController::class);
    Route::post('/hrd/grafKehadiran/', [HrdDashboardController::class, 'kehadiran'])->name('hrd.grafKehadiran');


    //Pegawai
    Route::get('/pegawai/restore/{data}', [PegawaiController::class, 'restore'])->name('pegawai.restore');
    Route::get('/pegawai/trash/', [PegawaiController::class, 'trash'])->name('pegawai.trash');
    Route::resource('pegawai', PegawaiController::class);
    Route::get('/pegawai/destroy/{data}', [PegawaiController::class, 'destroy'])->name('pegawai.destroy');
    Route::get('/pegawai/destroyPermanent/{data}', [PegawaiController::class, 'destroyPermanent'])->name('pegawai.destroyPermanent');


    //Jabatan
    Route::resource('jabatan', JabatanController::class);
    Route::get('/jabatan/destroy/{data}', [JabatanController::class, 'destroy'])->name('jabatan.destroy');


    //Divisi
    Route::resource('divisi', DivisiController::class);
    Route::get('/divisi/destroy/{data}', [DivisiController::class, 'destroy'])->name('divisi.destroy');


    //Presensi
    Route::get('/presensi/tanggal/', [PresensiHarianController::class, 'tglPresensi'])->name('presensi.search');
    Route::get('/presensi/template_download', [PresensiHarianController::class, 'download'])->name('presensi.template');
    Route::resource('/presensi', PresensiHarianController::class);
    Route::get('/presensi/destroy/{data}', [PresensiHarianController::class, 'destroy'])->name('presensi.destroy');
    Route::post('/presensi/import_excel', [PresensiHarianController::class, 'import'])->name('presensi.import');


    //Cuti
    Route::get('/cuti/tanggal/', [CutiController::class, 'tglPresensi'])->name('cuti.search');
    Route::get('/cuti/cutiBersama', [CutiController::class, 'cutiBersama'])->name('cuti.cutiBersama');
    Route::post('/cuti/cutiBersama/store', [CutiController::class, 'storeCutiBersama'])->name('cuti.storeCutiBersama');
    Route::resource('cuti', CutiController::class);
    Route::get('/cuti/destroy/{data}', [CutiController::class, 'destroy'])->name('cuti.destroy');
    Route::resource('hrdPengajuanCuti', HrdPengajuanCutiController::class); // pengajuan cuti tingkat HRD
    Route::put('/hrdPengajuanCuti/keputusan/{data}', [HrdPengajuanCutiController::class, 'keputusan'])->name('hrdPengajuanCuti.keputusan');


    //RiwayatJabatan
    Route::resource('riwayatJabatan', RiwayatJabatanController::class);
    Route::post('/riwayatJabatan/store', [RiwayatJabatanController::class, 'store'])->name('riwayatJabatan.store');
    Route::get('/riwayatJabatan/createData/{data}', [RiwayatJabatanController::class, 'createData'])->name('riwayatJabatan.createData');
    Route::get('/riwayatJabatan/destroy/{data}', [RiwayatJabatanController::class, 'destroy'])->name('riwayatJabatan.destroy');


    //RiwayatDivisi
    Route::resource('riwayatDivisi', RiwayatDivisiController::class);
    Route::post('/riwayatDivisi/store', [RiwayatDivisiController::class, 'store'])->name('riwayatDivisi.store');
    Route::get('/riwayatDivisi/createData/{data}', [RiwayatDivisiController::class, 'createData'])->name('riwayatDivisi.createData');
    Route::get('/riwayatDivisi/destroy/{data}', [RiwayatDivisiController::class, 'destroy'])->name('riwayatDivisi.destroy');


    //Kebijakan Jam Kerja & Cuti
    Route::resource('peraturan', PeraturanController::class);


    //Menu Staff
    Route::resource('staff', StaffDashboardController::class);
    Route::post('/staff/pres/', [StaffDashboardController::class, 'presensi'])->name('staff.presensi');
    Route::get('/staff/openFile/{data}', [StaffDashboardController::class, 'openFile'])->name('staff.openFile');


    //Menu Manajemen Role & Menu Dinamis
    Route::resource('role', RoleController::class);
    Route::get('/role/destroy/{data}', [RoleController::class, 'destroy'])->name('role.destroy');
    Route::patch('/role/update/{data}', [RoleController::class, 'update'])->name('role.update');

    Route::get('/manajemen', [ManajemenRoleMenuController::class, 'index'])->name('manajemen.index');

    Route::get('/manajemen/createMenu', [ManajemenRoleMenuController::class, 'createMenu'])->name('manajemen.createMenu');
    Route::post('/manajemen/storeMenu', [ManajemenRoleMenuController::class, 'storeMenu'])->name('manajemen.storeMenu');
    Route::get('/manajemen/{data}/editMenu', [ManajemenRoleMenuController::class, 'editMenu'])->name('manajemen.editMenu');
    Route::patch('/manajemen/{data}/updateMenu', [ManajemenRoleMenuController::class, 'updateMenu'])->name('manajemen.updateMenu');
    Route::get('/manajemen/{data}/destroyMenu', [ManajemenRoleMenuController::class, 'destroyMenu'])->name('manajemen.destroyMenu');

    Route::get('/manajemen/createHakAkses', [ManajemenRoleMenuController::class, 'createHakAkses'])->name('manajemen.createHakAkses');

resources/views/hrd/pengajuanCuti/details.blade.php
@extends('layout.base')

@section('title', 'Details Pengajuan Cuti')

@section('content_header')
    <div class="page-header page-header-default">
        <div class="page-header-content">
            <div class="page-title">
                <h4><i class="icon-furniture"></i> <span class="text-semibold">Data Cuti</span>
                    - Details Pengajuan Cuti</h4>
            </div>

        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li> <a href="{{ route('hrdPengajuanCuti.index') }}"> <i class="active icon-home2 position-left"></i> List
                        Pengajuan Cuti Pegawai
                    </a>
                </li>
                <li class="active">Details Pengajuan Cuti ID : {{ $cuti->id }} </li>
            </ul>
        </div>
    </div>
@endsection

@section('content')
    <div class="col-md-12">

        <div class="panel bg-info">
            <div class="panel-heading">
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
                <em>
                    <h6> Halaman ini menampilakan details data cuti, dan data pemohon cuti, setelah cuti Disetujui/Ditolak
                        sistem akan mengirimkan notifikasi berupa email ke alamat email pegawai
                        yang terdaftar.
                    </h6>
                </em>
            </div>
        </div>
    </div>

    <div class="col-md-5">
        <div class="panel ">
            <div class="panel-heading bg-info">
                <h5 class="panel-title text-center">Data Pemohon</h5>
            </div>

            <div class="panel-body">
                <div class="text-center">
                    @php $path =Storage::url('images/'.$cuti->pegawai->path); @endphp
                    <img src="{{ url($path) }}"
                        onerror="this.onerror=null; this.src='{{ URL::to('/admin/assets/images/brands/user.jpeg') }}'"
                        alt="Foto Profil" width="160">
                </div>
                <div class="mb-3"></div>
                <div class="table-responsive">
                    <table class="table table-xs">
                        <tr>
                            <td>Nama</td>
                            <td>:</td>
                            <td>{{ $cuti->pegawai->nama }}</td>
                        </tr>
                        <tr>
                            <td>Email</td>
                            <td>:</td>
                            <td>{{ $cuti->pegawai->email }}</td>
                        </tr>
                        <tr>
                            <td>Jabatan</td>
                            <td>:</td>
                            <td>{{ $cuti->pegawai->jabatan->nm_jabatan }}</td>
                        </tr>
                        <tr>
                            <td>Divisi</td>
                            <td>:</td>
                            <td>{{ $cuti->pegawai->divisi->nm_divisi }}</td>
                        </tr>

                    </table>
                </div>

            </div>
        </div>
    </div>

    <div class="col-md-7">
        <div class="panel">
            <div class="panel-heading bg-info">
                <h5 class="panel-title text-center">Data Cuti</h5>

            </div>

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <td><a href="" data-toggle="modal" data-target="#modal_iconified">
                                    <i class="icon-info22"></i> Lihat riwayat cuti pegawai</a></td>
                            <td></td>
                            <td></td>
                        </tr>
                        <tr>
                            <td>Tipe Cuti</td>
                            <td>:</td>
                            <td>{{ $cuti->tipe_cuti }}</td>
                        </tr>
                        <tr>
                            <td>Tanggal Pengajuan</td>
                            <td>:</td>
                            <td>{{ $cuti->tgl_pengajuan }}</td>
                        </tr>
                        <tr>
                            <td>Tanggal Mulai Cuti</td>
                            <td>:</td>
                            <td>{{ $cuti->tgl_mulai }}</td>
                        </tr>
                        <tr>
                            <td>Tanggal Selesai Cuti</td>
                            <td>:</td>
                            <td>{{ $cuti->tgl_selesai }}</td>
                        </tr>
                        <tr>
                            <td>Keterangan</td>
                            <td>:</td>
                            <td>{{ $cuti->ket }}</td>
                        </tr>
                        <tr>
                            <td>Atasan/Penanggung Jawab</td>
                            <td>:</td>
                            @if ($cuti->pegawai->id_atasan == null)
                                <td> Belum Ada Atasan </td>
                            @else
                                <td>{{ $cuti->pegawai->bawahan->nama }}</td>
                            @endif
                        </tr>
                        <tr>
                            <td>Disetujui Atasan</td>
                            <td>:</td>
                            @if ($cuti->pegawai->id_atasan == null)
                                <td> - </td>
                            @else
                                <td>{{ $cuti->tgl_disetujui_atasan }}</td>
                            @endif

                        </tr>

                    </table>
                </div>
            </div>
        </div>


        <div class="text-center">


            <form action="{{ route('hrdPengajuanCuti.keputusan', $id) }}" method="POST">
                {{ csrf_field() }}
                {{ method_field('PUT') }}

                <input type="text" name="tgl_mulai" value="{{ $cuti->tgl_mulai }}" hidden>
                <input type="text" name="tgl_selesai" value="{{ $cuti->tgl_selesai }}" hidden>
                <input type="text" name="id_pegawai" value="{{ $cuti->id_pegawai }}" hidden>
                <button class="btn btn-success" name="keputusan" type="submit" value="Disetujui HRD"> Setujui</button>
                <button class="btn btn-danger" name="keputusan" type="submit" value="Ditolak HRD"> Tolak</button>
            </form>
        </div>

    </div>

    <!-- Iconified modal -->
    <div id="modal_iconified" class="modal fade">
        <div class="modal-dialog ">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h5 class="modal-title"><i class="icon-info3"></i> &nbsp;Riwayat Data Cuti Pegawai Tahun Ini
                    </h5>
                </div>
                <div class="modal-body" id="list_item">
                    <div class="row">
                        <div class="col">
                            <legend class="text-bold"></i> A. Riwayat Cuti Terakhir
                            </legend>
                        </div>
                        <table id="classTable" class="table ">
                            <thead>
                                <tr>
                                    <th> No</th>
                                    <th> Tanggal Mulai</th>
                                    <th> Tanggal Selesai</th>
                                    <th> Tipe Cuti </th>
                                    <th> Keterangan</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $i = 1; ?>
                                @if ($riwayatCuti->count())
                                    @foreach ($riwayatCuti as $item)
                                        <tr>
                                            <td>{{ $i++ }}</td>
                                            <td>{{ $item->tgl_mulai }}</td>
                                            <td>{{ $item->tgl_selesai }}</td>
                                            <td>{{ $item->tipe_cuti }}</td>
                                            <td>{{ $item->ket }}</td>
                                        </tr>
                                    @endforeach
                                @else
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td>Belum ada data</td>
                                        <td></td>
                                @endif
                            </tbody>
                        </table>
                    </div>

                    <div class="mt-3"></div>
                    <div class="row">
                        <div class="col">
                            <legend class="text-bold"></i> B. Detail Cuti Terpakai
                            </legend>
                        </div>
                        <table id="classTable" class="table ">
                            <thead>
                                <tr>
                                    <th> Tahunan</th>
                                    <th> Bersama</th>
                                    <th> Penting</th>
                                    <th> Besar </th>
                                    <th> Sakit</th>
                                    <th> Hamil</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php $i = 1; ?>
                                <tr>
                                    <td>{{ $cutiTahunan . ' / ' . $batasTahunan }}</td>
                                    <td>{{ $cutiBersama . ' / ' . $batasBersama }}</td>
                                    <td>{{ $cutiPenting . ' / ' . $batasPenting }}</td>
                                    <td>{{ $cutiBesar . ' / ' . $batasBesar }}</td>
                                    <td>{{ $cutiSakit . ' / ' . $batasSakit }}</td>
                                    <td>{{ $cutiHamil . ' / ' . $batasHamil }}</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                </div>

            </div>
        </div>
    </div>
    <!-- /iconified modal -->
@endsection

resources/views/hrd/pengajuanCuti/index.blade.php
@extends('layout.base')


@section('title', 'Data Cuti')


@section('content_header')
    <div class="page-header page-header-default">
        <div class="page-header-content">
            <div class="page-title">
                <h4><i class="icon-furniture"></i> <span class="text-semibold">Data Cuti</span>
                    - Pengajuan Cuti</h4>
            </div>

        </div>

        <div class="breadcrumb-line">
            <ul class="breadcrumb">
                <li><i class="active icon-home2 position-left"></i> List Pengajuan Cuti Pegawai</li>
                {{-- <li class="active">Dashboard</li> --}}
            </ul>
        </div>
    </div>
@endsection

@section('content')
    <div class="row">
        <div class="panel bg-info">
            <div class="panel-heading">
                <div class="heading-elements">
                    <ul class="icons-list">
                        <li><a data-action="close"></a></li>
                    </ul>
                </div>
                <em>
                    <h6> Halaman ini menampilkan daftar pengajuan cuti pegawai yang sudah disetujui atasan pegawai,
                        dan langkah selanjutnya harus disetujui oleh HRD.
                        <br>Untuk <b>Menyetujui</b> atau <b>Menolak</b> pengajuan cuti silahkan klik tombol "lihat".
                    </h6>
                </em>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="panel panel-flat">
                <div class="panel-heading">
                </div>

                <div class="panel-body">

                    <table class="table datatable-basic table-bordered table-striped table-hover table-xs">
                        <thead class="bg-primary">
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Tipe Cuti</th>
                                <th>Tgl Pengajuan</th>
                                <th>Keterangan</th>
                                <th class="text-center">Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $i = 1; ?>
                            @if ($pengajuan->count())
                                @foreach ($pengajuan as $key => $p)
                                    <tr>
                                        <td>{{ $i++ }}</td>
                                        <td>{{ $p->pegawai->nama }}</td>
                                        <td>{{ $p->tipe_cuti }}</td>
                                        <td>{{ $p->tgl_pengajuan }}</td>
                                        <td>{{ $p->ket }}</td>
                                        <td class="text-center">
                                            <?php $encyrpt = Crypt::encryptString($p->id); ?>
                                            <a href="{{ route('hrdPengajuanCuti.show', $encyrpt) }}"
                                                class="btn btn bg-info-300"><i class=" icon-eye"></i> Lihat
                                            </a>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <!-- /basic datatable -->
@endsection